name: Run Selenium Script

on:
  push:

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install undetected-chromedriver

    - name: Install Browser and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser wget unzip
        wget -q https://chromedriver.storage.googleapis.com/LATEST_RELEASE -O LATEST_RELEASE
        CHROME_DRIVER_VERSION=$(cat LATEST_RELEASE)
        wget https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver_linux64.zip LATEST_RELEASE

    - name: Run Selenium Script
      run: python3 app.py
