name: Run Selenium Script

on:
  workflow_dispatch:

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade undetected-chromedriver selenium

    - name: Install Chrome and matching ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        CHROME_VERSION=$(chromium-browser --version | awk '{print $2}' | cut -d '.' -f 1-3)
        DRIVER_VERSION=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json" | jq -r ".channels.Stable.versions | map(select(.version | startswith(\"$CHROME_VERSION\")))[0].version")
        curl -Lo chromedriver.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip"
        unzip chromedriver.zip -d /usr/local/bin/

    - name: Run Selenium script
      run: python app.py
