name: Playwright Automation

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright beautifulsoup4

    - name: Install Playwright Browsers
      run: playwright install

    - name: Run Playwright Script
      run: python aa.py

    - name: Upload Screenshot
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: screenshot.png  # Path to the screenshot file
