name: Run Selenium Script

on:
  workflow_dispatch:

jobs:
  selenium-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install undetected-chromedriver

    - name: Install Chrome and ChromeDriver
      run: |
        # Install Chrome 114
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        rm google-chrome-stable_current_amd64.deb

        # Install ChromeDriver 114
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver_linux64.zip

    - name: Run Selenium Script
      run: python3 app.py
