name: Run Selenium Script

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install undetected-chromedriver selenium

    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y chromium-chromedriver
        echo 'export PATH=$PATH:/usr/lib/chromium-browser/' >> $GITHUB_ENV

    - name: Run Selenium script
      run: python app.py
