name: Google Login Automation
on:
  workflow_dispatch:  # Manually triggered
jobs:
  google-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver selenium
      
      - name: Install Chrome and ChromeDriver
        run: |
          # Update package lists
          sudo apt-get update
          
          # Install Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -y -f
          
          # Get Chrome version
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
          
          # Fetch the latest ChromeDriver version compatible with Chrome
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          
          # Download ChromeDriver
          wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          
          # Unzip and install ChromeDriver
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
      
      - name: Debug Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version
      
      - name: Run Google Login Script
        run: python app.py
      
      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: login-screenshots
          path: screenshots/
        if: always()  # Upload screenshots even if the job fails
