name: Run Playwright Script

on:
  workflow_dispatch:  # Manually triggered

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4

      - name: Install Playwright browsers
        run: |
          playwright install

      - name: Install Xvfb (for virtual display)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Run Playwright script with Xvfb
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python app.py

      - name: Upload Screenshots (if any)
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/
        if: always()  # Upload screenshots even if the job fails
