name: Scraping Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker image
        run: |
          docker build -t my-scraping-app .

      - name: Run the scraping container
        run: |
          docker run my-scraping-app
          
      - name: Debug Screenshots Directory
        run: |
          ls -R screenshots

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: login-screenshots
          path: screenshots/
        if: always()
