name: Run Selenium Script

on:
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser wget unzip jq
        mkdir -p /home/runner/snap/chromium/common/.cache

    - name: Setup ChromeDriver
      run: |
        CHROME_VERSION=$(chromium-browser --version | awk '{print $2}')
        wget https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver_linux64.zip

    - name: Run Selenium Script
      run: |
        python3 app.py
