name: Run Playwright Script

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the workflow
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Playwright Script
        run: |
          docker run nuel000/fb
